### ISSUE TITLE
开了一个-f自动测试，"请求频率超限，请稍后再试"

### ISSUE THREAD

**Issue by BrunuhVille** [xgadget-lab/nexttrace#35]
你好
就进行一个-f的自动测试，脚本就显示多次的"请求频率超限，请稍后再试"

可否改善一下

**Comment by sjlleo** [comment]
感谢反馈，有朋友反馈出结果太快还没来得及看就直接被下个测试刷掉了，而且过快的大量请求IP对API服务器造成了很大的压力，下个版本应该会改成每次路由跟踪结束后会等待5秒再进行下一次测试。

**Comment by sjlleo** [comment]
28c29614902496b8063f73f917b67d219be808f4
[update: improve fast test](https://github.com/xgadget-lab/nexttrace/commit/28c29614902496b8063f73f917b67d219be808f4)
增加了提示的颜色，排版略作改动

已经发布了 `v0.1.10` 版本，请再试试哦

**Comment by sjlleo** [comment]
如果没有问题，此issue将被关闭。

**Comment by Weltolk** [comment]
同样的问题，自动测试第一次选了三网，因为测试的节点太多了，所以结束了进程，第二次想测试单ISP，结果一直提示这个

**Comment by tsosunchia** [comment]
> 同样的问题，自动测试第一次选了三网，因为测试的节点太多了，所以结束了进程，第二次想测试单ISP，结果一直提示这个

对于批量测试，我们不鼓励频繁执行

（如果版本较低，也建议升级到最新版本

**Comment by Weltolk** [comment]
> > 同样的问题，自动测试第一次选了三网，因为测试的节点太多了，所以结束了进程，第二次想测试单ISP，结果一直提示这个
> 
> 对于批量测试，我们不鼓励频繁执行
> 
> （如果版本较低，也建议升级到最新版本

是最新版，请问大概多久能进行下一次测试？

**Comment by tsosunchia** [comment]
> > > 同样的问题，自动测试第一次选了三网，因为测试的节点太多了，所以结束了进程，第二次想测试单ISP，结果一直提示这个
> > 
> > 
> > 对于批量测试，我们不鼓励频繁执行
> > （如果版本较低，也建议升级到最新版本
> 
> 是最新版，请问大概多久能进行下一次测试？

跟你的网络环境也有关，一般来说冷却1个小时大概就没问题了
