### ISSUE TITLE
当一个域名有多个 IP 时，默认选择第一个 IPv4 地址，按回车即可查询

### ISSUE THREAD

**Issue by atzlinux** [xgadget-lab/nexttrace#37]
当一个域名有多个 IP 时，默认选择第一个 IPv4 地址，按回车即可查询。不需要自己再输入 0 或者 1 了。

**Comment by sjlleo** [comment]
您好，

选择功能是我们的特色功能，因为很多用户有选择IP的需求，所以特别做了这样一个功能，您可以直接回车，默认会选择第一个IP。

Thanks

Best Regards,
Leo Shen

**Comment by sjlleo** [comment]
没有这个必要，如果需要知道逻辑的话，直接看源代码就可以了。我们自认为现在文档已经非常完善，非常照顾新人，这个 feature 没有在文档里显示也没有问题。对于交互性页面，用户就算遇到了也应该能懂得如何操作。
