### ISSUE TITLE
Privide musl build for Linux in GitHub release

### ISSUE THREAD

**Issue by hronro** [xgadget-lab/nexttrace#39]
Some Linux distros use musl as libc, and currently the pre-build binaries in GitHub releases are not able to run on those distros.

**Comment by tsosunchia** [comment]
@hronro 可以提供一些更详细的报错信息嘛？

**Comment by sjlleo** [comment]
@tsosunchia 看起来是外国人

**Comment by hronro** [comment]
@tsosunchia The OS simply refused to run it, no other error info.

**Comment by tsosunchia** [comment]
我们似乎已经找到了解决方案，请从这里下载测试版，看看问题是否解决
https://api.leo.moe/tracemap/html/dist/nexttrace_linux_amd64

**Comment by sjlleo** [comment]
@tsosunchia 你咋知道他用的一定是×86_64
