### ISSUE TITLE
-bash: ./nexttrace_linux_amd64: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by lalalaod** [xgadget-lab/nexttrace#7]
根本打不开

**Comment by tsosunchia** [comment]
请提交完整的截图，包括您输入的命令。

**Comment by lalalaod** [comment]
脚本不安全

**Comment by tsosunchia** [comment]
>>脚本不安全
麻烦你具体说明

**Comment by fkx4-p** [comment]
According to your error, this is a problem caused by you, you have downloaded the wrong binary file, please check the error message on Google before you ask questions here in the issues sector.

**Comment by fkx4-p** [comment]
> 脚本不安全

And yes, you have the right to not use the script, but please learn more about Linux and make Google searches before asking here.

**Comment by tsosunchia** [comment]
> > 脚本不安全
> 
> And yes, you have the right to not use the script, but please learn more about Linux and make Google searches before asking here.

大佬消消气，这位可能真是小白不太懂
@[lalalaod](https://github.com/lalalaod) 请您详尽说明一下问题，我们才好帮你解决

**Comment by tsosunchia** [comment]
由于此issue不符合issue提交规范，将自动关闭。
如有更多问题，请重新按模版提交。
